### ISSUE TITLE
Kinesis Analytics application having downtime after migrating to Kinesis connector v2 but no error is reported

### ISSUE THREAD

**Issue by cbm-egoubely** [aws/aws-kinesisanalytics-flink-connectors#13] opened 2020-09-28 15:37 UTC
Hello,
I have just migrated to Kinesis connector v2 and my Flink application works within my local Flink cluster but when I deploy it to Kinesis Data Analytics the application is having downtime and no error is reported.

I switched KDA log level to DEBUG and the only possibly relevant log is this one:

<details>
<summary>Relevant error log</summary>
`
{"locationInformation":"org.apache.flink.runtime.exceptionclassifier.ExceptionClassifier.classify(ExceptionClassifier.java:112)","logger":"org.apache.flink.runtime.exceptionclassifier.ExceptionClassifier","message":"Exception type is USER from filter results [UserClassLoaderExceptionFilter -> NONE, UserAPIExceptionFilter -> NONE, UserSerializationExceptionFilter -> USER, UserFunctionExceptionFilter -> SKIPPED, OutOfMemoryExceptionFilter -> NONE, TooManyOpenFilesExceptionFilter -> NONE, KinesisServiceExceptionFilter -> NONE].","throwableInformation":["org.apache.flink.streaming.runtime.tasks.StreamTaskException: Cannot instantiate user function.","\tat org.apache.flink.streaming.api.graph.StreamConfig.getStreamOperator(StreamConfig.java:239)","\tat org.apache.flink.streaming.runtime.tasks.OperatorChain.createChainedOperator(OperatorChain.java:369)","\tat org.apache.flink.streaming.runtime.tasks.OperatorChain.createOutputCollector(OperatorChain.java:296)","\tat org.apache.flink.streaming.runtime.tasks.OperatorChain.createChainedOperator(OperatorChain.java:360)","\tat org.apache.flink.streaming.runtime.tasks.OperatorChain.createOutputCollector(OperatorChain.java:296)","\tat org.apache.flink.streaming.runtime.tasks.OperatorChain.createChainedOperator(OperatorChain.java:360)","\tat org.apache.flink.streaming.runtime.tasks.OperatorChain.createOutputCollector(OperatorChain.java:296)","\tat org.apache.flink.streaming.runtime.tasks.OperatorChain.<init>(OperatorChain.java:133)","\tat org.apache.flink.streaming.runtime.tasks.StreamTask.invoke(StreamTask.java:275)","\tat org.apache.flink.runtime.taskmanager.Task.run(Task.java:714)","\tat java.lang.Thread.run(Thread.java:748)","Caused by: java.io.InvalidClassException: com.fasterxml.jackson.databind.AnnotationIntrospector; local class incompatible: stream classdesc serialVersionUID = -1733064445206768782, local class serialVersionUID = -8026823904936543468","\tat java.io.ObjectStreamClass.initNonProxy(ObjectStreamClass.java:699)","\tat java.io.ObjectInputStream.readNonProxyDesc(ObjectInputStream.java:1964)","\tat java.io.ObjectInputStream.readClassDesc(ObjectInputStream.java:1830)","\tat java.io.ObjectInputStream.readNonProxyDesc(ObjectInputStream.java:1964)","\tat java.io.ObjectInputStream.readClassDesc(ObjectInputStream.java:1830)","\tat java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2121)","\tat java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1647)","\tat java.io.ObjectInputStream.defaultReadFields(ObjectInputStream.java:2366)","\tat java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:2290)","\tat java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2148)","\tat java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1647)","\tat java.io.ObjectInputStream.defaultReadFields(ObjectInputStream.java:2366)","\tat java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:2290)","\tat java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2148)","\tat java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1647)","\tat java.io.ObjectInputStream.defaultReadFields(ObjectInputStream.java:2366)","\tat java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:2290)","\tat java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2148)","\tat java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1647)","\tat java.io.ObjectInputStream.readArray(ObjectInputStream.java:2054)","\tat java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1635)","\tat java.io.ObjectInputStream.defaultReadFields(ObjectInputStream.java:2366)","\tat java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:2290)","\tat java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2148)","\tat java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1647)","\tat java.io.ObjectInputStream.defaultReadFields(ObjectInputStream.java:2366)","\tat java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:2290)","\tat java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2148)","\tat java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1647)","\tat java.io.ObjectInputStream.readObject(ObjectInputStream.java:483)","\tat java.io.ObjectInputStream.readObject(ObjectInputStream.java:441)","\tat org.apache.flink.util.InstantiationUtil.deserializeObject(InstantiationUtil.java:566)","\tat org.apache.flink.util.InstantiationUtil.deserializeObject(InstantiationUtil.java:552)","\tat org.apache.flink.util.InstantiationUtil.deserializeObject(InstantiationUtil.java:540)","\tat org.apache.flink.util.InstantiationUtil.readObjectFromConfig(InstantiationUtil.java:501)","\tat org.apache.flink.streaming.api.graph.StreamConfig.getStreamOperator(StreamConfig.java:224)","\t... 10 more"],"threadName":"flink-akka.actor.default-dispatcher-167","applicationVersionId":"64","messageSchemaVersion":"1","messageType":"INFO"}
`
</details>

<details>
<summary>pom.xml I used for the app module</summary>
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>fr.cbm</groupId>
    <artifactId>lc-logs-bus</artifactId>
    <version>1.0-SNAPSHOT</version>
    <packaging>jar</packaging>

    <properties>
        <mainClass>fr.cbm.EventDispatcherStreamingJob</mainClass>
        <java.version>1.8</java.version>
        <scala.binary.version>2.11</scala.binary.version>
        <flink.version>1.8.3</flink.version>
        <kda.version>1.1.0</kda.version>
        <kda-connector.version>2.0.0</kda-connector.version>
        <jackson.version>2.7.9</jackson.version>
    </properties>

    <dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>com.amazonaws</groupId>
                <artifactId>aws-java-sdk-bom</artifactId>
                <version>1.11.870O</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
        </dependencies>
    </dependencyManagement>

    <dependencies>
        <dependency>
            <groupId>com.amazonaws</groupId>
            <artifactId>aws-java-sdk-dynamodb</artifactId>
        </dependency>

        <dependency>
            <groupId>com.amazonaws</groupId>
            <artifactId>aws-kinesisanalytics-runtime</artifactId>
            <version>${kda.version}</version>
        </dependency>

        <dependency>
            <groupId>org.apache.flink</groupId>
            <artifactId>flink-connector-kinesis_${scala.binary.version}</artifactId>
            <version>${flink.version}</version>
        </dependency>

        <dependency>
            <groupId>org.apache.flink</groupId>
            <artifactId>flink-streaming-java_${scala.binary.version}</artifactId>
            <version>${flink.version}</version>
            <scope>provided</scope>
        </dependency>

        <dependency>
            <groupId>com.amazonaws</groupId>
            <artifactId>aws-kinesisanalytics-flink</artifactId>
            <version>${kda-connector.version}</version>
        </dependency>

        <dependency>
            <groupId>com.amazonaws</groupId>
            <artifactId>aws-java-sdk-logs</artifactId>
        </dependency>

        <dependency>
            <groupId>com.amazonaws</groupId>
            <artifactId>aws-java-sdk-sts</artifactId>
        </dependency>

        <dependency>
            <groupId>com.fasterxml.jackson.core</groupId>
            <artifactId>jackson-core</artifactId>
            <version>${jackson.version}</version>
        </dependency>

        <dependency>
            <groupId>com.fasterxml.jackson.datatype</groupId>
            <artifactId>jackson-datatype-jdk8</artifactId>
            <version>${jackson.version}</version>
        </dependency>

        <dependency>
            <groupId>com.fasterxml.jackson.module</groupId>
            <artifactId>jackson-module-parameter-names</artifactId>
            <version>${jackson.version}</version>
        </dependency>

        <dependency>
            <groupId>com.fasterxml.jackson.datatype</groupId>
            <artifactId>jackson-datatype-jsr310</artifactId>
            <version>${jackson.version}</version>
        </dependency>

        <dependency>
            <groupId>org.junit.jupiter</groupId>
            <artifactId>junit-jupiter-api</artifactId>
            <version>5.6.0</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.junit.jupiter</groupId>
            <artifactId>junit-jupiter-engine</artifactId>
            <version>5.6.0</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.slf4j</groupId>
            <artifactId>slf4j-api</artifactId>
            <version>1.7.16</version>
        </dependency>

        
        <dependency>
            <groupId>commons-lang</groupId>
            <artifactId>commons-lang</artifactId>
            <version>2.6</version>
        </dependency>

    </dependencies>

    <build>

        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
                <version>3.1</version>
                <configuration>
                    <source>${java.version}</source>
                    <target>${java.version}</target>
                </configuration>
            </plugin>

            <plugin>
                <artifactId>maven-surefire-plugin</artifactId>
                <version>2.22.2</version>
            </plugin>

            
            
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-shade-plugin</artifactId>
                <version>3.0.0</version>
                <executions>
                    
                    <execution>
                        <phase>package</phase>
                        <goals>
                            <goal>shade</goal>
                        </goals>
                        <configuration>
                            <artifactSet>
                                <excludes>
                                    <exclude>org.apache.flink:force-shading</exclude>
                                    <exclude>org.slf4j:*</exclude>
                                    <exclude>log4j:*</exclude>
                                </excludes>
                            </artifactSet>
                            <filters>
                                <filter>
                                    
                                    <artifact>*:*</artifact>
                                    <excludes>
                                        <exclude>META-INF/*.SF</exclude>
                                        <exclude>META-INF/*.DSA</exclude>
                                        <exclude>META-INF/*.RSA</exclude>
                                    </excludes>
                                </filter>
                            </filters>
                            <transformers>
                                <transformer
                                        implementation="org.apache.maven.plugins.shade.resource.ManifestResourceTransformer">
                                    <mainClass>${mainClass}</mainClass>
                                </transformer>
                            </transformers>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
        </plugins>
    </build>
</project>
</details>

**Comment by dannycranmer** [comment] 2020-09-28 16:40
Hello @cbm-egoubely, are you saying the application worked ok on KDA using version `v1.1.0` and you only experienced the issue after upgrading to `v2.0.0`? It looks like the app is failing to resume from a snapshot due to mismatch in the serialised state. I am investigating this issue and will keep you posted.

**Comment by cbm-egoubely** [comment] 2020-09-28 17:38
Yes @dannycranmer this is correct, the application was working on `v1.1.0` and the only change I have made is bump the lib to `v2.0.0`. 
Thank you for your quick reply, I can provide more information if needed.

**Comment by cbm-egoubely** [comment] 2020-09-29 12:12
For information, snapshots were disabled in my KDA application configuration.

**Comment by dannycranmer** [comment] 2020-09-29 12:14
Hey @cbm-egoubely. I have tried and failed to reproduce this. I have performed the following successfully:
- Deploy app using `v1.1.0` to KDA
- Run application, stop application
- Update app to use `v2.0.0`, resume from snapshot when restarting
- Run application, stop application
- Update app to use `v1.1.0`, resume from snapshot when restarting

Your latest comment just popped up and has debunked my theory. I assumed it was failing to restore from old snapshot. In this case did you modify any of the Jackson versions between runs?

**Comment by dannycranmer** [comment] 2020-09-30 07:34
This error indicates that the object has been serialized with a different version of the `AnnotationIntrospector` on the client than it is being deserialized on the server. Can you please provide the before and after `pom` to enable me to investigate further?

**Comment by cbm-egoubely** [comment] 2020-09-30 14:16
Thank you for investigating this.

No, I didn't change Jacksons versions. Here are the two `pom.xml` versions. The only difference is the `aws-kinesisanalytics-flink` version so I don't think it will help

Original pom.xml:

```
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>fr.cbm</groupId>
    <artifactId>lc-logs-bus</artifactId>
    <version>1.0-SNAPSHOT</version>
    <packaging>jar</packaging>

    <properties>
        <mainClass>fr.cbm.EventDispatcherStreamingJob</mainClass>
        <java.version>1.8</java.version>
        <scala.binary.version>2.11</scala.binary.version>
        <flink.version>1.8.3</flink.version>
        <kda.version>1.1.0</kda.version>
        <jackson.version>2.7.9</jackson.version>
    </properties>

    <dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>com.amazonaws</groupId>
                <artifactId>aws-java-sdk-bom</artifactId>
                <version>1.11.379</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
        </dependencies>
    </dependencyManagement>

    <dependencies>
        <dependency>
            <groupId>com.amazonaws</groupId>
            <artifactId>aws-java-sdk-dynamodb</artifactId>
        </dependency>

        <dependency>
            <groupId>com.amazonaws</groupId>
            <artifactId>aws-kinesisanalytics-runtime</artifactId>
            <version>${kda.version}</version>
        </dependency>

        <dependency>
            <groupId>org.apache.flink</groupId>
            <artifactId>flink-connector-kinesis_${scala.binary.version}</artifactId>
            <version>${flink.version}</version>
        </dependency>

        <dependency>
            <groupId>org.apache.flink</groupId>
            <artifactId>flink-streaming-java_${scala.binary.version}</artifactId>
            <version>${flink.version}</version>
            <scope>provided</scope>
        </dependency>

        <dependency>
            <groupId>com.amazonaws</groupId>
            <artifactId>aws-kinesisanalytics-flink</artifactId>
            <version>${kda.version}</version>
        </dependency>

        <dependency>
            <groupId>com.amazonaws</groupId>
            <artifactId>aws-java-sdk-logs</artifactId>
        </dependency>

        <dependency>
            <groupId>com.amazonaws</groupId>
            <artifactId>aws-java-sdk-sts</artifactId>
        </dependency>

        <dependency>
            <groupId>com.fasterxml.jackson.core</groupId>
            <artifactId>jackson-core</artifactId>
            <version>${jackson.version}</version>
        </dependency>

        <dependency>
            <groupId>com.fasterxml.jackson.datatype</groupId>
            <artifactId>jackson-datatype-jdk8</artifactId>
            <version>${jackson.version}</version>
        </dependency>

        <dependency>
            <groupId>com.fasterxml.jackson.module</groupId>
            <artifactId>jackson-module-parameter-names</artifactId>
            <version>${jackson.version}</version>
        </dependency>

        <dependency>
            <groupId>com.fasterxml.jackson.datatype</groupId>
            <artifactId>jackson-datatype-jsr310</artifactId>
            <version>${jackson.version}</version>
        </dependency>

        <dependency>
            <groupId>org.junit.jupiter</groupId>
            <artifactId>junit-jupiter-api</artifactId>
            <version>5.6.0</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.junit.jupiter</groupId>
            <artifactId>junit-jupiter-engine</artifactId>
            <version>5.6.0</version>
            <scope>test</scope>
        </dependency>
    </dependencies>

    <build>

        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
                <version>3.1</version>
                <configuration>
                    <source>${java.version}</source>
                    <target>${java.version}</target>
                </configuration>
            </plugin>

            <plugin>
                <artifactId>maven-surefire-plugin</artifactId>
                <version>2.22.2</version>
            </plugin>

            <!-- We use the maven-shade plugin to create a fat jar that contains all necessary dependencies. -->
            <!-- Change the value of <mainClass>...</mainClass> if your program entry point changes. -->
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-shade-plugin</artifactId>
                <version>3.0.0</version>
                <executions>
                    <!-- Run shade goal on package phase -->
                    <execution>
                        <phase>package</phase>
                        <goals>
                            <goal>shade</goal>
                        </goals>
                        <configuration>
                            <artifactSet>
                                <excludes>
                                    <exclude>org.apache.flink:force-shading</exclude>
                                    <exclude>org.slf4j:*</exclude>
                                    <exclude>log4j:*</exclude>
                                </excludes>
                            </artifactSet>
                            <filters>
                                <filter>
                                    <!-- Do not copy the signatures in the META-INF folder.
                                    Otherwise, this might cause SecurityExceptions when using the JAR. -->
                                    <artifact>*:*</artifact>
                                    <excludes>
                                        <exclude>META-INF/*.SF</exclude>
                                        <exclude>META-INF/*.DSA</exclude>
                                        <exclude>META-INF/*.RSA</exclude>
                                    </excludes>
                                </filter>
                            </filters>
                            <transformers>
                                <transformer
                                        implementation="org.apache.maven.plugins.shade.resource.ManifestResourceTransformer">
                                    <mainClass>${mainClass}</mainClass>
                                </transformer>
                            </transformers>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
        </plugins>
    </build>
</project>
```

Updated `pom.xml`:

```
<groupId>fr.cbm</groupId>
<artifactId>lc-logs-bus</artifactId>
<version>1.0-SNAPSHOT</version>
<packaging>jar</packaging>

<properties>
    <mainClass>fr.cbm.EventDispatcherStreamingJob</mainClass>
    <java.version>1.8</java.version>
    <scala.binary.version>2.11</scala.binary.version>
    <flink.version>1.8.3</flink.version>
    <kda.version>1.1.0</kda.version>
    <kda-connector.version>2.0.0</kda-connector.version>
    <jackson.version>2.7.9</jackson.version>
</properties>

<dependencyManagement>
    <dependencies>
        <dependency>
            <groupId>com.amazonaws</groupId>
            <artifactId>aws-java-sdk-bom</artifactId>
            <version>1.11.870O</version>
            <type>pom</type>
            <scope>import</scope>
        </dependency>
    </dependencies>
</dependencyManagement>

<dependencies>
    <dependency>
        <groupId>com.amazonaws</groupId>
        <artifactId>aws-java-sdk-dynamodb</artifactId>
    </dependency>

    <dependency>
        <groupId>com.amazonaws</groupId>
        <artifactId>aws-kinesisanalytics-runtime</artifactId>
        <version>${kda.version}</version>
    </dependency>

    <dependency>
        <groupId>org.apache.flink</groupId>
        <artifactId>flink-connector-kinesis_${scala.binary.version}</artifactId>
        <version>${flink.version}</version>
    </dependency>

    <dependency>
        <groupId>org.apache.flink</groupId>
        <artifactId>flink-streaming-java_${scala.binary.version}</artifactId>
        <version>${flink.version}</version>
        <scope>provided</scope>
    </dependency>

    <dependency>
        <groupId>com.amazonaws</groupId>
        <artifactId>aws-kinesisanalytics-flink</artifactId>
        <version>${kda-connector.version}</version>
    </dependency>

    <dependency>
        <groupId>com.amazonaws</groupId>
        <artifactId>aws-java-sdk-logs</artifactId>
    </dependency>

    <dependency>
        <groupId>com.amazonaws</groupId>
        <artifactId>aws-java-sdk-sts</artifactId>
    </dependency>

    <dependency>
        <groupId>com.fasterxml.jackson.core</groupId>
        <artifactId>jackson-core</artifactId>
        <version>${jackson.version}</version>
    </dependency>

    <dependency>
        <groupId>com.fasterxml.jackson.datatype</groupId>
        <artifactId>jackson-datatype-jdk8</artifactId>
        <version>${jackson.version}</version>
    </dependency>

    <dependency>
        <groupId>com.fasterxml.jackson.module</groupId>
        <artifactId>jackson-module-parameter-names</artifactId>
        <version>${jackson.version}</version>
    </dependency>

    <dependency>
        <groupId>com.fasterxml.jackson.datatype</groupId>
        <artifactId>jackson-datatype-jsr310</artifactId>
        <version>${jackson.version}</version>
    </dependency>

    <dependency>
        <groupId>org.junit.jupiter</groupId>
        <artifactId>junit-jupiter-api</artifactId>
        <version>5.6.0</version>
        <scope>test</scope>
    </dependency>
    <dependency>
        <groupId>org.junit.jupiter</groupId>
        <artifactId>junit-jupiter-engine</artifactId>
        <version>5.6.0</version>
        <scope>test</scope>
    </dependency>
    <dependency>
        <groupId>org.slf4j</groupId>
        <artifactId>slf4j-api</artifactId>
        <version>1.7.16</version>
    </dependency>

    <!-- https://mvnrepository.com/artifact/commons-lang/commons-lang -->
    <dependency>
        <groupId>commons-lang</groupId>
        <artifactId>commons-lang</artifactId>
        <version>2.6</version>
    </dependency>

</dependencies>

<build>

    <plugins>
        <plugin>
            <groupId>org.apache.maven.plugins</groupId>
            <artifactId>maven-compiler-plugin</artifactId>
            <version>3.1</version>
            <configuration>
                <source>${java.version}</source>
                <target>${java.version}</target>
            </configuration>
        </plugin>

        <plugin>
            <artifactId>maven-surefire-plugin</artifactId>
            <version>2.22.2</version>
        </plugin>

        <!-- We use the maven-shade plugin to create a fat jar that contains all necessary dependencies. -->
        <!-- Change the value of <mainClass>...</mainClass> if your program entry point changes. -->
        <plugin>
            <groupId>org.apache.maven.plugins</groupId>
            <artifactId>maven-shade-plugin</artifactId>
            <version>3.0.0</version>
            <executions>
                <!-- Run shade goal on package phase -->
                <execution>
                    <phase>package</phase>
                    <goals>
                        <goal>shade</goal>
                    </goals>
                    <configuration>
                        <artifactSet>
                            <excludes>
                                <exclude>org.apache.flink:force-shading</exclude>
                                <exclude>org.slf4j:*</exclude>
                                <exclude>log4j:*</exclude>
                            </excludes>
                        </artifactSet>
                        <filters>
                            <filter>
                                <!-- Do not copy the signatures in the META-INF folder.
                                Otherwise, this might cause SecurityExceptions when using the JAR. -->
                                <artifact>*:*</artifact>
                                <excludes>
                                    <exclude>META-INF/*.SF</exclude>
                                    <exclude>META-INF/*.DSA</exclude>
                                    <exclude>META-INF/*.RSA</exclude>
                                </excludes>
                            </filter>
                        </filters>
                        <transformers>
                            <transformer
                                    implementation="org.apache.maven.plugins.shade.resource.ManifestResourceTransformer">
                                <mainClass>${mainClass}</mainClass>
                            </transformer>
                        </transformers>
                    </configuration>
                </execution>
            </executions>
        </plugin>
    </plugins>
</build>
```

Also, I dont know if it's relevant but in the dependency tree of the project, I notice there are two Jacksons versions (2.7.9 and 2.6.7) used:
```
[INFO] --- maven-dependency-plugin:2.8:tree (default-cli) @ lc-logs-bus ---
[INFO] fr.cbm:lc-logs-bus:jar:1.0-SNAPSHOT
[INFO] +- com.amazonaws:aws-java-sdk-dynamodb:jar:1.11.379:compile
[INFO] |  +- com.amazonaws:aws-java-sdk-s3:jar:1.11.379:compile
[INFO] |  |  \- com.amazonaws:aws-java-sdk-kms:jar:1.11.379:compile
[INFO] |  +- com.amazonaws:aws-java-sdk-core:jar:1.11.379:compile
[INFO] |  |  +- commons-logging:commons-logging:jar:1.1.3:compile
[INFO] |  |  +- org.apache.httpcomponents:httpclient:jar:4.5.5:compile
[INFO] |  |  |  +- org.apache.httpcomponents:httpcore:jar:4.4.9:compile
[INFO] |  |  |  \- commons-codec:commons-codec:jar:1.10:compile
[INFO] |  |  +- software.amazon.ion:ion-java:jar:1.0.2:compile
[INFO] |  |  +- com.fasterxml.jackson.dataformat:jackson-dataformat-cbor:jar:2.6.7:compile
[INFO] |  |  \- joda-time:joda-time:jar:2.8.1:compile
[INFO] |  \- com.amazonaws:jmespath-java:jar:1.11.379:compile
[INFO] +- com.amazonaws:aws-kinesisanalytics-runtime:jar:1.1.0:compile
[INFO] |  +- org.slf4j:slf4j-log4j12:jar:1.7.7:runtime
[INFO] |  |  \- log4j:log4j:jar:1.2.17:runtime
[INFO] |  \- org.apache.flink:flink-shaded-jackson:jar:2.7.9-4.0:compile
[INFO] +- org.apache.flink:flink-connector-kinesis_2.11:jar:1.8.3:compile
[INFO] +- org.apache.flink:flink-streaming-java_2.11:jar:1.8.3:provided
[INFO] |  +- org.apache.flink:flink-runtime_2.11:jar:1.8.3:provided
[INFO] |  |  +- org.apache.flink:flink-core:jar:1.8.3:provided
[INFO] |  |  |  +- org.apache.flink:flink-annotations:jar:1.8.3:provided
[INFO] |  |  |  +- org.apache.flink:flink-metrics-core:jar:1.8.3:provided
[INFO] |  |  |  +- com.esotericsoftware.kryo:kryo:jar:2.24.0:provided
[INFO] |  |  |  |  +- com.esotericsoftware.minlog:minlog:jar:1.2:provided
[INFO] |  |  |  |  \- org.objenesis:objenesis:jar:2.1:provided
[INFO] |  |  |  +- commons-collections:commons-collections:jar:3.2.2:provided
[INFO] |  |  |  \- org.apache.commons:commons-compress:jar:1.18:provided
[INFO] |  |  +- org.apache.flink:flink-java:jar:1.8.3:provided
[INFO] |  |  |  \- org.apache.flink:flink-shaded-asm-6:jar:6.2.1-6.0:provided
[INFO] |  |  +- org.apache.flink:flink-queryable-state-client-java_2.11:jar:1.8.3:provided
[INFO] |  |  +- org.apache.flink:flink-hadoop-fs:jar:1.8.3:provided
[INFO] |  |  +- commons-io:commons-io:jar:2.4:provided
[INFO] |  |  +- org.apache.flink:flink-shaded-netty:jar:4.1.32.Final-6.0:provided
[INFO] |  |  +- org.apache.flink:flink-shaded-asm:jar:5.0.4-6.0:provided
[INFO] |  |  +- org.apache.commons:commons-lang3:jar:3.3.2:provided
[INFO] |  |  +- commons-cli:commons-cli:jar:1.3.1:provided
[INFO] |  |  +- org.javassist:javassist:jar:3.19.0-GA:provided
[INFO] |  |  +- org.scala-lang:scala-library:jar:2.11.12:provided
[INFO] |  |  +- com.typesafe.akka:akka-actor_2.11:jar:2.4.20:provided
[INFO] |  |  |  +- com.typesafe:config:jar:1.3.0:provided
[INFO] |  |  |  \- org.scala-lang.modules:scala-java8-compat_2.11:jar:0.7.0:provided
[INFO] |  |  +- com.typesafe.akka:akka-stream_2.11:jar:2.4.20:provided
[INFO] |  |  |  +- org.reactivestreams:reactive-streams:jar:1.0.0:provided
[INFO] |  |  |  \- com.typesafe:ssl-config-core_2.11:jar:0.2.1:provided
[INFO] |  |  |     \- org.scala-lang.modules:scala-parser-combinators_2.11:jar:1.0.4:provided
[INFO] |  |  +- com.typesafe.akka:akka-protobuf_2.11:jar:2.4.20:provided
[INFO] |  |  +- com.typesafe.akka:akka-slf4j_2.11:jar:2.4.20:provided
[INFO] |  |  +- org.clapper:grizzled-slf4j_2.11:jar:1.3.2:provided
[INFO] |  |  +- com.github.scopt:scopt_2.11:jar:3.5.0:provided
[INFO] |  |  +- org.xerial.snappy:snappy-java:jar:1.1.4:provided
[INFO] |  |  \- com.twitter:chill_2.11:jar:0.7.6:provided
[INFO] |  |     \- com.twitter:chill-java:jar:0.7.6:provided
[INFO] |  +- org.apache.flink:flink-clients_2.11:jar:1.8.3:provided
[INFO] |  |  \- org.apache.flink:flink-optimizer_2.11:jar:1.8.3:provided
[INFO] |  +- org.apache.flink:flink-shaded-guava:jar:18.0-6.0:provided
[INFO] |  +- org.apache.commons:commons-math3:jar:3.5:provided
[INFO] |  +- com.google.code.findbugs:jsr305:jar:1.3.9:provided
[INFO] |  \- org.apache.flink:force-shading:jar:1.8.3:provided
[INFO] +- com.amazonaws:aws-kinesisanalytics-flink:jar:2.0.0:compile
[INFO] |  +- com.amazonaws:aws-java-sdk-iam:jar:1.11.379:compile
[INFO] |  \- com.amazonaws:aws-java-sdk-kinesis:jar:1.11.379:compile
[INFO] +- com.amazonaws:aws-java-sdk-logs:jar:1.11.379:compile
[INFO] +- com.amazonaws:aws-java-sdk-sts:jar:1.11.379:compile
[INFO] +- com.fasterxml.jackson.core:jackson-core:jar:2.7.9:compile
[INFO] +- com.fasterxml.jackson.datatype:jackson-datatype-jdk8:jar:2.7.9:compile
[INFO] |  \- com.fasterxml.jackson.core:jackson-databind:jar:2.7.9:compile
[INFO] |     \- com.fasterxml.jackson.core:jackson-annotations:jar:2.7.0:compile
[INFO] +- com.fasterxml.jackson.module:jackson-module-parameter-names:jar:2.7.9:compile
[INFO] +- com.fasterxml.jackson.datatype:jackson-datatype-jsr310:jar:2.7.9:compile
[INFO] +- org.junit.jupiter:junit-jupiter-api:jar:5.6.0:test
[INFO] |  +- org.apiguardian:apiguardian-api:jar:1.1.0:test
[INFO] |  +- org.opentest4j:opentest4j:jar:1.2.0:test
[INFO] |  \- org.junit.platform:junit-platform-commons:jar:1.6.0:test
[INFO] +- org.junit.jupiter:junit-jupiter-engine:jar:5.6.0:test
[INFO] |  \- org.junit.platform:junit-platform-engine:jar:1.6.0:test
[INFO] +- org.slf4j:slf4j-api:jar:1.7.16:compile
[INFO] \- commons-lang:commons-lang:jar:2.6:compile
```

The other beeing added by the dynamodb sdk, I will try removing these dependencies and see if it makes a difference.

**Comment by dannycranmer** [comment] 2020-11-18 14:37
Hey @cbm-egoubely, did you get anywhere with this?

**Comment by dannycranmer** [comment] 2021-02-09 10:59
Resolving since there has not been any updates on this. Please reopen if still a problem

**Closed by dannycranmer** 2021-02-09 10:59 UTC
